name: anihd
description: A new Flutter project.

publish_to: 'none' 

version: 2.0.3+2

environment:
  sdk: '>=3.1.0-102.0.dev <4.0.0'

dependencies:
  gallery_saver: ^2.3.2
  uuid: ^3.0.7
  once: '1.5.3'
  envied: ^0.3.0+3
  equatable: ^2.0.5
  sqflite: '2.2.8+3'
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.7.0
  dio: any
  rename: ^2.1.1  
  flutter_cache_manager: ^3.3.1
  flutter_wallpaper_manager: ^0.0.4
  permission_handler: ^10.4.3
  flutter_file_dialog: ^3.0.2
  share_plus: ^7.1.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  path_provider: ^2.1.1

  google_mobile_ads: ^3.0.0

  sizer: ^2.0.15
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  envied_generator: ^0.3.0+3
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  # image_path: 'assets/img/logo_512x512.png'
  adaptive_icon_background: '#542161'
  image_path_android: 'assets/img/logo_1080x1080.png'
  image_path_ios: 'assets/img/ios_logo.png'
  adaptive_icon_foreground: 'assets/img/foreground_1024.png'

flutter:

  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Londrina
      fonts:
        - asset: assets/fonts/LondrinaSolid-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700